name: QQ阅读

on:
  schedule:
    - cron: '*/10 * * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requests'
        run: pip install requests

      - name: 'run QQ阅读'
        # qq_speed.py目录自己修改
        run: python3 quanx/qq_speed.py
        env:
            QQREAD_BODY1: ${{ secrets.QQREAD_BODY1 }}  #必须 账号1 readBody
            QQREAD_TIMEHD1: ${{ secrets.QQREAD_TIMEHD1 }}  #必须 账号1 timeHeader
            QQREAD_TIMEURL1: ${{ secrets.QQREAD_TIMEURL1 }}  #必须 账号1 timeUrl
            QQREAD_BODY2: ${{ secrets.QQREAD_BODY2 }}  #非必须 账号2 readBody
            QQREAD_TIMEHD2: ${{ secrets.QQREAD_TIMEHD2 }}  #非必须 账号2 timeHeader
            QQREAD_TIMEURL2: ${{ secrets.QQREAD_TIMEURL2 }}  #非必须 账号2 timeUrl
            WITHDRAW: ${{ secrets.WITHDRAW }}  #非必须 是否自动提现10
            BARK: ${{ secrets.BARK }}  #非必须 bark通知
            SCKEY: ${{ secrets.SCKEY }}  #非必须 server酱通知
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}  #非必须 tg机器人token
            TG_USER_ID: ${{ secrets.TG_USER_ID }}  #非必须 tg机器人userId
            DD_BOT_ACCESS_TOKEN: ${{ secrets.DD_BOT_ACCESS_TOKEN }}  #非必须 钉钉机器人token
            DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}  #非必须 钉钉机器人secret
